### ISSUE TITLE
Process terminated with exit code 1

### ISSUE THREAD

**Issue by rmfberlin** [katgirl/isotope_german#1]
I would like to install via contao-manager isotope/isotope_german after isotope/isotope-core and isotope/isotope_documents. 

Installation of isotope/isotope-core and isotope/isotope_documents was without any errors.

Process terminated with exit code 1
Reason: General error

Exception occured: Could not find a matching version of package isotope/isotope_german. Check the package spelling, your version constraint and that the package is available in a stability which matches your minimum-stability (stable).

**Comment by katgirl** [comment]
it give no tags, please select ```master```
