### ISSUE TITLE
Error installing under Contao 4.4.20 and isotope-core 2.5.1 install not possible

### ISSUE THREAD

**Issue by sempervivum3000** [katgirl/isotope_german#2]
Error installing under Contao 4.4.20 and isotope-core 2.5.1
Error output from the Contao console is:
$ /usr/bin/php7.2 '-q' '/var/public/c44/web/contao-manager.phar.php' 'composer' 'require' 'isotope/isotope_german' '--no-progress' '--no-suggest' '--no-update' '--no-scripts' '--prefer-stable' '--sort-packages' '--no-ansi' '--no-interaction' 2>&1

In InitCommand.php line 718:
                                                                               
  Could not find a version of package isotope/isotope_german matching your mi  
  nimum-stability (stable). Require it with an explicit version constraint al  
  lowing its desired stability.                                                
                                                                               

require [--dev] [--prefer-source] [--prefer-dist] [--no-progress] [--no-suggest] [--no-update] [--no-scripts] [--update-no-dev] [--update-with-dependencies] [--update-with-all-dependencies] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--] [<packages>]...

# Process terminated with exit code 1
# Result: General error

**Comment by katgirl** [comment]
it give no tags, please select ```master```
